server:
  port: 3000
spring:
  redis:
    host: 192.168.124.23
    port: 6379
  application:
    name: wzf-crowd-redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/